### ISSUE TITLE
Not found some area

### ISSUE THREAD

**Issue by suwat-netprom** [yiminzme/Multi-Highlight#14]
This best ulitity tools , I to try find text some time not found example dynamics text, new dom html.

![2021-10-14_00-33-49](https://user-images.githubusercontent.com/14134992/137185384-8829a160-a8c4-4cd6-88f2-040493e8cd3d.png)

**Comment by yiminzme** [comment]
Yes, multi-highlight won't work well on all dynamic webpage. it is because the dynamic content is loaded after the web page is loaded. multi-highlight doesn't track when the webpage has a new dynamic content load, so it won't update dynamically.
you can change the text in the popup textbox to trigger search action after your dynamic content is load.
